### PR TITLE
[WIP] Add information about first meet up

### PR DESCRIPTION
**Pull request by jnbt**
**This is work-in-progress**

Add some real information to our homepage:
- Information about next meet up 
  - [x] Date & Time
  - [x] Talks & Speakers
  - [x] Location
  - [ ] Sponsors?
- Meta infos
  - [x] Gitter
  - [x] GitHub
  - [x] Twitter
- Legal stuff
  - [x] Imprint
  - [x] Privacy policy (EU)

### CODE REVIEW

**Comment by jnbt** [comment]
**Edit**: Use http://gh-pages-pr-2.preview.elixir.ruhr/ to preview

Old screenshot: https://cloud.githubusercontent.com/assets/678542/12112413/b94ce83e-b39c-11e5-84da-2ff44c7f9ec1.png

**Comment by jnbt** [comment]
I've just added our company to the "Impressum" just to have it filled. This can be discussed, if someone doesn't want "Neopoly" to be mentioned here.

/cc @ElixirRuhr/core

**Comment by rrrene** [comment]
:+1: looks great!

**Comment by splattael** [comment]
See live preview: http://gh-pages-pr-2.preview.elixir.ruhr/

**Comment by splattael** [comment]
:sparkles: nice!

**Comment by jnbt** [comment]
@c-rack can you provide a short title for your topic and a photo?

**Comment by c-rack** [comment]
I'd like to talk about _"Job scheduling in Elixir"_, slides will be in English, talk will be in German.
Please find a photo here: ﻿﻿http://www.constantin-rack.com/photo_256x256.jpg
Also, please fix the typo `﻿﻿stumpled -> stumbled` in my description, thanks.

**Comment by rrrene** [comment]
+1 for "slides in English, talk in german". We don't introduce artificial language barriers, but will be able to upload the slides to e.g. [SpeakerDeck](https://speakerdeck.com/) for those who want to review past meetups in the future. :+1:

**Pull request merged**
