### PR TITLE
Upgrade most of the dependencies

### PR DESCRIPTION
**Pull request by splattael**
As GitHub has warned us about "potential security vulnerabilities" is
our dependencies I'd like to upgrade some of them.

The idea behind pinning `bourbon` and `neat` is to make the diff as
focused as possible.

### CODE REVIEW

**Comment by jnbt** [comment]
I'll try to re-trigger the CI system by closing and re-opening the PR

**Comment by splattael** [comment]
@jnbt https://github.com/ElixirRuhr/elixir.ruhr/pull/15/commits/9e7ccfadc002c453cbe474ebcc2d50ea0f010ae2 could go on `master` directly, couldn't it?

**Review by jnbt — APPROVED** [review]
I've done a manual test to build the site on my machine and this works ✨ 
So I think we can merge now, but until #18 is done the deploy won't work.

**Comment by splattael** [comment]
@jnbt Thanks for the review!

I'd like to wait for #18 to verify that our workflow to preview pull requests on e.g. http://gh-pages-pr-14.preview.elixir.ruhr still works. WDYT?

**Comment by jnbt** [comment]
@splattael Agreed. I'm currently trying to fix the process

**Comment by splattael** [comment]
@jnbt Awesome,thank you :yellow_heart:

**Comment by jnbt** [comment]
@splattael I've rebased and forced-pushed. Let wait if the preview build is working now.

**Comment by splattael** [comment]
http://gh-pages-pr-15.preview.elixir.ruhr/

**Comment by jnbt** [comment]
LGTM

**Comment by splattael** [comment]
Waiting for ElixirRuhr/preview-website/pull/2 to be merged :twisted_rightwards_arrows:

**Pull request merged**
