### PR TITLE
Fix Git LFS on Travis

### PR DESCRIPTION
**Pull request by jnbt**

### CODE REVIEW

**Comment by jnbt** [comment]
http://gh-pages-pr-18.preview.elixir.ruhr

**Comment by splattael** [comment]
:purple_heart:

**Comment by jnbt** [comment]
@splattael Seems to fixed. Preview is working only the images are still not working due to the "git-raw" hack which doesn't work for Git LFS

**Review by splattael — APPROVED** [review]

**Comment by splattael** [comment]
@jnbt I'll try to fix this Git LFS issue.

**Pull request merged**
