### PR TITLE
Extract meetup archive and add navigation

### PR DESCRIPTION
**Pull request by jnbt**
- Add meetup archive
- Add navigation
- Start extracting common content
- Add first gallery

PREVIEW: http://gh-pages-pr-5.preview.elixir.ruhr/

### CODE REVIEW

**Comment by jnbt** [comment]
@splattael Please have a look at the preview system. Following URL isn't found http://gh-pages-pr-5.preview.elixir.ruhr/meetups/001-where-to-start/

**Comment by splattael** [comment]
@jnbt Thanks for the head-ups!

Fixed in ElixirRuhr/preview-website@454a5ee

**Comment by jnbt** [comment]
Reopen because of real issue of this issue

**Comment by splattael** [comment]
Oops, sorry for that :fearful:

**Comment by splattael** [comment]
Maybe we could show the sponsors on the frontpage as well?

**Comment by splattael** [comment]
LGTM!

**Pull request merged**
