### PR TITLE
Add first impressions to 2nd meetup

### PR DESCRIPTION
**Pull request by JanOwiesniak**

### CODE REVIEW

**Comment by JanOwiesniak** [comment]
2nd meetup looks good to me but it seems like i somehow messed up images from 1st meetup.
Any idea what is going on here?

**001**
http://gh-pages-pr-14.preview.elixir.ruhr/meetups/001-where-to-start/

**002**
http://gh-pages-pr-14.preview.elixir.ruhr/meetups/002-embedded-systems-with-nerves/

/cc @jnbt @splattael

**Comment by splattael** [comment]
:+1:

**Comment by splattael** [comment]
Maybe it's rawgit's fault?

https://raw.githubusercontent.com/ElixirRuhr/elixir.ruhr/gh-pages-pr-14/images/galleries/001/large/img_0001.jpg shows:

```
version https://git-lfs.github.com/spec/v1
oid sha256:5ce9b92b8db728231040dcff4a7f1b95d7796398fd80f9109f6a843a14ca6494
size 85315
```

**Comment by JanOwiesniak** [comment]
:+1:

**Comment by jnbt** [comment]
I suspect Git LFS to be the issue here as the raw git information only includes a reference to an URL + metadata

**Pull request merged**
